### ISSUE TITLE
Add method drop-down for Discharge field

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#104]
mahumeetod
ujukimeetod
silma järgi hinnatud
ülevooluga
kasutades mingit mõõteseadet

**Comment by ailimadisson** [comment]
how is discharge method names in english?

**Comment by JTerasmaa** [comment]
Siin on tabel, kuhu ma olen pannud lisandunud tõlkimis tvajavad väljendid. Loodetavasti lätlased tõlgivad ka kohe-kohe asjad ära.
https://docs.google.com/spreadsheets/d/1uRgPSdyobEXpgucf7l5HynvlvrnBtCXoVQOS7LgNcNc/edit#gid=0

Kui sul ka mingeid sõnu silma jääb lehel, mis kõikides keeltes pole, siis pane ka sinna samasse.
