### ISSUE TITLE
Replace minimap on the landing page

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#110]
New image https://www.dropbox.com/sh/bpwpkn506zsax7x/AABB2sva1YRPWvWB27yZ-IUWa?dl=0&preview=allikad.info_manual_ENG.png

& link to the user manual (https://allikad.info/instructions)

<img width="883" alt="Screenshot 2021-04-16 at 11 20 55" src="https://user-images.githubusercontent.com/380007/114994946-00cb1100-9ea6-11eb-9358-6edc245a0b89.png">

**Comment by ailimadisson** [comment]
As I Understood, this image link should refer to pdf https://www.dropbox.com/sh/bpwpkn506zsax7x/AABB2sva1YRPWvWB27yZ-IUWa?dl=0&preview=allikad.info_manual_EST.pdf
