### ISSUE TITLE
Editors are able to mark Spring as "not a spring"

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#113]
<img width="980" alt="Screenshot 2021-04-16 at 11 34 53" src="https://user-images.githubusercontent.com/380007/114996754-cebaae80-9ea7-11eb-8fdb-178935dc9b87.png">

**Comment by ailimadisson** [comment]
done. commit 2dc0b27de1921c84fc5ac8f7a77822149b37d737
