### ISSUE TITLE
Wateract landing page

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#14]
![Screenshot 2020-11-04 at 13 14 27](https://user-images.githubusercontent.com/380007/98104845-b299f680-1e9f-11eb-9499-7521d822de35.png)

Most popular = Featured

**Comment by JTerasmaa** [comment]
Kas seal võiks kohe olla ka nt nime järgi otsingu väli. 

Selline vaade võiks ka tulevikus kuhugi edasi jääda, kui landing page olemas. A la asuda hoopis allikad.info/kaart vms. Äkki hetkel ka sellisele alamdomeenile tõsta ja pealeht lihtsalt sinna suunata.

Infost, mida allika juures pildi all kuvatakse - Ownership ei ole vast oluline. 
Parem näiteks Spring classification, Status.
Ja Location kuni küla/asumi tasemele Estonia, Harjumaa, Muraste vms

**Comment by tammets** [comment]
> Kas seal võiks kohe olla ka nt nime järgi otsingu väli.
> 
> Selline vaade võiks ka tulevikus kuhugi edasi jääda, kui landing page olemas. A la asuda hoopis allikad.info/kaart vms. Äkki hetkel ka sellisele alamdomeenile tõsta ja pealeht lihtsalt sinna suunata.
> 
> Infost, mida allika juures pildi all kuvatakse - Ownership ei ole vast oluline.
> Parem näiteks Spring classification, Status.
> Ja Location kuni küla/asumi tasemele Estonia, Harjumaa, Muraste vms

Updated 04/11/20
