### ISSUE TITLE
URL ja linkimine sotsiaalmeediasse

### ISSUE THREAD

**Issue by JTerasmaa** [centre-for-educational-technology/wateract#16]
Nagu ma aru saan, siis kõik allikad saavad unikaalse URLi. URLis olev number võiks olla Wateracti kood.

Kas iga sellise kirje jagamiseks saab olla vastava allika lehele ka nupuke FBs ja Insagramis jagamise jaoks?

**Comment by tammets** [comment]
> Kas iga sellise kirje jagamiseks saab olla vastava allika lehele ka nupuke FBs ja Insagramis jagamise jaoks?

Minu andmetel Instagrammi veebirakendusest midagi jagada ei saa. See toimib vaid Androidi/iOSi native rakenduste puhul.

**Comment by tammets** [comment]
Duplicates #17 and #18
