### ISSUE TITLE
Display static data layers for main map view

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#39]
Layers are:

Kult allikad - Muinsuskaitsealused allikad
LD_allikad - Loodusdirektiivi allikaelupaigad
Pär_allikad - Pärandkultuuriallikad
Seire_allikad - Allikate seirejaamad
VEP_allikad - Allikalised vääriselupaigad
ÜOB_allikad - Looduskaitsealused allikad
Ürg_allikad - Ürglooduse raamatu allikad

https://drive.google.com/drive/folders/1hkebi8xla8mL6qdNDk6CDy5UclfCB5CL?usp=sharing

**Comment by JTerasmaa** [comment]
See on ikka jube tähtis asi, mida väga kaugele tulevikku ei saa lükata. Läbi nende staatiliste kaardikihtide tulevad kasutajate jaoks allikate otsingupiirkonna jms. Ehket kuhu tasub minna uusi allikaid otsima.

Äkki saame läbi rääkida ja selle 1.1-te tagasi.
