### ISSUE TITLE
User roles and rights

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#4]
**Registered (logged in) user (Spring enthusiast)**

1. Add new springs
2. Add new observations
3. Modify own items as long these are on "Saved" status. Added spring will be public after publishing by user (#5)

**Editor**

1. Edit / delete observations ja measurements
3. Edit / delete springs
3. Change a status of the spring
4. Add KKR code

**Administrator**

1. Assign user roles
2. All editor's rights (without county limitations)

**Comment by JTerasmaa** [comment]
Editor
Kas Editorilde saab anda asukohapõhiseid piiranguid. Mulle see Marko ettepane meeldis. Et nt saab ainult kindlate maakondade allikaid muuta ja kinnitada, mitte kogu andmebaasi piires. Ja neid ruumilis õiguseid saab siis juurde anda või ära võtta. Nii et sisuliselt Administraatori vaates on Editori juures maakondade nimekiri, milles tuleb panna linnukesi ette.

Administrator
tal on ikka kõik Editori õigused + Assign user roles?

**Comment by ailimadisson** [comment]
Adminil ikkagi editori õigusi ei oleks. Aga kasutajal võib olla mitu rolli, ta võib olla nii editor kui admin.

**Comment by JTerasmaa** [comment]
Ok, siis sobib nii ka. Peaasi, et ei peaks rolle või kasutajaid vms vahetama hakkama, kui vaja ühte või teist toimingut teostada.

Aga kas asukohapõhised piirangud on mõeldav lähenemine?

**Comment by JTerasmaa** [comment]
Lisaks Admin roll peaks olema ka midagi stiilis
 - confirm Editors submissions
- return Editors submissions for corrections
- change Editors submissions

või midagi umbes sellist. Ehket see roll peab võimaldama ka Editoride tööd kontrollida ja vajadusel ülevaatamiseks/täiendamiseks tagasi saatma ja lisaks võimalus neid muuta.

**Comment by mvainu** [comment]
Mõtlesime koos Jaanusega veel selle õiguste asja ning sellega seoses ka mõnede lahtrite asukohad läbi ning tervikidee on järgmine. 
Olenevalt kasutajast võiks ta saada sujuvalt oma rolli kas Registered user, Editor või Administrator vahel vahetada, nii, nagu ÕISis, et üleval paremal on rippmenüü, kus saab valida, kas ma olen parasjagu üliõpilane, õppejõud, või erinevate õppekavade administraator. Siis ei pea mingeid hübriidkombinatsioone tekitama. Reaalsuses saab üks inimene olla samal ajal nii Editor kui Administrator ja nende vahel ümber lülitada, kuid samal ajal Registered user ja Editor olla ei ole suurt mõtet. Registered User asemel võiks kasutada näiteks nimetust Spring enthusiast ehk eesti keeles Allikahuviline.

Uue allika lisamisel ehk "Add new" lehel on nii Spring enthusiast kui Editor rolli korral ühed ja samad väljad, need on Name, Location, Latitude, Longitude, Photos, Reference, Description ja Folklore. "Add additional info" lehel olevate andmete sisestamise võimalus peaks ka olema juba uue allika sisestamisel, ilmselt siis noolest lahti klikitava lahendusena. County ja Settlement lahtreid pole "Add new" lehel vaja näidata, kuna need pole kasutaja poolt muudetavad, vaid täituvad koordinaadi järgi automaatselt infoga pärast seda, kui uus allikas on salvestatud ehk vajutatud nuppu "Save" või esitatud kinnitamiseks nupuga "Submit". Kinnitamiseks saab allikaid esitada ka kohe ilma eelnevalt salvestamata, kuid kummagi nupu juures peab olema küsimärgiga pop-up infokast, mis selgitab kummagi nupu tagajärgi. Pärast seda lähevad salvestatud või esitatud allikad kusagile "Minu allikad/My springs" leheküljel olevasse nimekirja, kus saab salvestatud "Save" allikate puhul infot veel muuta "Edit" ning need siis ära esitada "Submit". Ilmselt peaks seal "Edit" nupu all avanema sama lehekülg, nagu "Single spring view landing" lehel "Edit" nuppu vajutades, ainult, et vähemate lahtritega. 

Seal "Minu allikad/My springs" lehel peaks olema ka kaardiaken, kus kõigile muudele standardsetele allikate kaardikihtidele lisaks on ka kaardikiht ainult nende allikatega, mida konkreetne kasutaja on lisanud. Ideaalis võiks sellel kihil olevad allikad olla erivärvilised sõltuvad sellest, kas need on staatuses "Saved", "Submitted", "Confirmed in allikad.info" või "Confirmed in environmental registry". 

Neile tegevustele lisaks saab Spring enthusiast lisada uusi vaatlusandmeid/observations juba allikad.info rakenduses olemas olevatele allikatele. See peaks käima vist ainult "Single spring view landing" lehekülje kaudu, kuhu Spring enthusiast pääseb avalehel oleval kaardil olevate allikate kaudu. Et seal Observations sakil on lisaks juba sisestatud andmetele ka nupp "Add new observations". Või on võimalik teha ka nii, et avalehel on "Add new spring" kõrval ka valik "Add new observation", kus avaneb see "Add additional info" sisestusvorm. Sellisel juhul peab aga välja mõtlema, kuidas seda sisestusvormi õige allikaga siduda. Vahepealne variant oleks, et avalehel oleval kaardil allikapunkti peale klikkides avanevas infoaknas on nupp "Add new observation", mis viib vaatlusandmete sisestamise lehele ja on juba klikitud allika koordinaatidega seotud. Nagu sisestatud uute allikate puhul, peaks ka vaatlusandmete puhul olema võimalik valida kaks varianti "Submit" ja "Save". Kuna me rääkisime, et vaatlusandmed võiksid minna kohe ilma kontrollimata avalikuks, siis nemad Editori töölauale ei jõua.

Need kasutaja poolt lisatud vaatlused peaksid sarnaselt lisatud allikatele kogunema eraldi nimekirja, mis asub menüüs "My observations/Minu vaatlused", mille ülesehitus ja sisu on sarnased "My springs"'ile.

Lisaks saab Spring enthusiast anda allikad.info rakenduses olevatele allikate kohta tagasidet "Single spring view landing" leheküljel oleva nupuga "Feedback". Sinna saab kirjutada erinevaid täiendus- ja parandusettepanekuid nii asukoha kui teksti kohta. Tagasiside andmine on ka ainuke sisendav tegevus, mida registreerimata kasutaja rakenduses teha saab. Seega nende kahe rollikirjeldused on järgmised:

**Unregistered user**
- Give feedback to all the springs in the database.  

**Spring enthusiast**
- Add new springs, including the following info: Name, Coordinates, Photos, Reference, Description, Folklore
- Add new data on the sheet "Add additional information" to all the springs in the database
- Modify own springs and observation data as long these are in "Saved" status. Added spring will be public after being submitted by user
- Give feedback to all the springs in the database.   

Editoridele jagatakse õigusi maakondade kaupa. Ühel Editoril võib olla hallata mitu maakonda, meie TLÜs saame kõigi maakondade Editorideks. Editor rollis kasutajatel peaks selle "My springs" all olema menüükirje "Spring editing/Allikate toimetamine". Seal peaks avanema nimekiri kõigist konkreetse Editori haldusmaakonnas/maakondades olevatest allikatest, kusjuures nimekirja ülemises osas peaksid olema need allikad, mis on saadetud kinnitamisele. Kaardiaken ka, kus kõigile muudele standardsetele allikate kaardikihtidele lisaks on ka kaardikiht ainult nende allikatega, mis on konkreetse Editori halduspiirkonnas. Ideaalis võiks sellel kihil olevad allikad olla erivärvilised sõltuvad sellest, kas need on staatuses "Submitted/Unconfirmed", "Confirmed in allikad.info", "Confirmed in environmental registry", "Needing special attention/Erakorralist ülekontrolli". Sealt nimekirjast (kuna topeltvariant, et nii kaardiobjekti infoaknast kui nimekirjast, on vist võimatu) saavad nad avada allikate "Edit" lehe, kus lisaks "Add new" lehel olevatele lahtritele on lisaks ka kõiki ülejäänud praegu "Add new" lehel olevad lahtrid: KKR Code, Link with other databases, Spring classification, Groundwater body, Geology, Ownership, Status, mida nad kõike täita saavad ja see on ka koht, kus nad saavad allikaid kinnitada ehk muuta nende staatust. 

Kuna Editor võib ise allikaid kaardistada igal pool, kuid kinnitada saab ainult konkreetses maakonnas, siis ei saagi Editori jaoks kõik need lahtrid juba "Add new" lehel olemas olla, sest sellel hetkel ei saa allikaid veel maakonna järgi sorteerida. Kui Editor on oma vaatluse salvestanud või esitanud ja see saab juurde maakonnainfo, siis liigub see kas talle endale kinnitamiseks ehk "Spring editing" menüüsse või mõnele teisele Editorile kinnitamiseks. Võib mõelda, kas Editoril võiks avaneda juba "My springs" menüüs olevate tema maakonda jäävate allikate juures "Edit" nuppu vajutades täispikk nimekiri muudetavaid lahtreid, sest selleks hetkeks on neil maakonnainfo juba küljes või on seal ikkagi ainult lühike variant (nagu Spring enthusiastil) ning kõigi lahtrite juurde pääseb ta ainult "Spring editing" menüüs olevate allikate ja iga üksiku allika "Single spring view landing" leheküljel oleva "Edit" nupu kaudu. Ka see igal üksikul "Single spring view landing" lehel olev "Edit" nupp peab nähtav olema vaid selle maakonna allikatel, mille haldaja konkreetne Editor on. 

"Spring editing" menüüs olevate allikate juures, mille staatus on "Submitted", peaks olema nupp "Send back to submittee", millega Editor saab puuduliku infoga allika selle esitajale koos kommentaaride ja lisaküsimustega tagasi saata.

Lisaks peaks Editoril olema seal "Spring editing" allikate nimekirja allikate juures nupp "Add measurable data". Neid andmeid saab lisada ainult Editor ja ainult nende allikate kohta, mis tema halduspiirkonda jäävad. Või kui sinna seda nuppu mitte panna, siis ilmselt peaks nende andmete lisamine käima nii, et see nupp on Editori halduspiirkonnas olevate allikate "Single spring view landing" lehel Measurement sakil. Või kolmas variant oleks, et Editorid saavad "Add new measurement" lehele avalehelt ühel neist kahest viisist, mida on kirjeldatud Spring enthusiast juures "Add new observation"'iga seoses ehk kas avalehel oleva nupu kaudu või avalehe kaardi allikapunktide infoaknas oleva nupu kaudu. 

Seega Editori rollikirjeldus oleks järgmine:
**Editor**
- Add new springs, including the following info: Name, Coordinates, Photos, Reference, Description, Folklore
- Add new data on the sheet "Add additional information" to all the springs in the database
- Modify own springs and observation data as long these are in "Saved" status. Added spring will be public after being submitted by user
- Give feedback to all the springs in the database.   
- Edit / delete springs in his/her county
- Add / edit all the data of the springs in his/her county (sheets View, Observations, Measurements)
- Send a spring in his/her county back to the submittee for amendments with added comments what to improve or clarify

**Administrator**
- Assign user roles

**Comment by tammets** [comment]
**Registered User:**

- add springs
- edit / delete own springs as long it’s draft
- add observations
- edit /delete own observations as long it’s draft

**Editor:**

- add springs
- edit / delete own springs as long it’s draft
- edit / delete springs that are in the same county as marked in user's profile.
- add observations
- edit /delete own observations as long it’s draft
- edit / delete observations that are in the same county as marked in user's profile.
- add measurements
- edit /delete own measurements as long it’s draft
- edit / delete measurements that are in the same county as marked in user's profile.

**Admin:**

- add / edit / delete springs
- add / edit / delete observations
- add / edit /delete measurements
