### ISSUE TITLE
Display user's name who added spring

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#49]
Visible only for logged-in user

https://zcpvr1.axshare.com/#id=rehdap&p=single-spring-view-landing&g=1

![Screenshot 2021-01-08 at 19 18 53](https://user-images.githubusercontent.com/380007/104044840-63957800-51e6-11eb-98ac-79d7ec29e5bc.png)

**Comment by ailimadisson** [comment]
Those springs that were imported from file don't have creator. So not showing label 'added by' if spring was imported.
