### ISSUE TITLE
Users are unable to set profile image

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#60]
![Unknown](https://user-images.githubusercontent.com/380007/107344245-eb62f080-6aca-11eb-8bb2-262d9b9fbc84.png)

![Screenshot 2021-02-09 at 11 35 23](https://user-images.githubusercontent.com/380007/107344260-f158d180-6aca-11eb-9351-b4e405ad967d.png)

**Comment by ailimadisson** [comment]
fixed
