### ISSUE TITLE
Add "pan to current location" to main map

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#62]
![Screenshot 2021-02-15 at 14 23 38](https://user-images.githubusercontent.com/380007/107946378-a262de80-6f99-11eb-9d38-b9f66d43e65a.png)

**Comment by ailimadisson** [comment]
commit e5a3509ed0e2dd1d053daf12da95251778e8cacf and commit c8ae4edb6a22627eba60903418030dc3593a72de
