### ISSUE TITLE
Users are able to add news items

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/wateract#97]
Users in admin role are able to add News items:

![Screenshot 2021-03-22 at 17 45 38](https://user-images.githubusercontent.com/380007/112108734-4bb07c00-8bb9-11eb-9015-3f43ab65abcd.png)

News item consists of title, body text and date (automatically generated after publishing)

![Screenshot 2021-03-23 at 09 22 20](https://user-images.githubusercontent.com/380007/112108846-700c5880-8bb9-11eb-9d58-97840719dbd5.png)

**Comment by ailimadisson** [comment]
As I remember there should also be locale dropdown. News are displayed based on locale.

**Comment by tammets** [comment]
> As I remember there should also be locale dropdown. News are displayed based on locale.

News are based on locale (only news corresponding to UI language are being displayed).
